// =============================================
//  PoliTo Analisi Studio v2 - Data Layer
//  Percorsi aggiornati: materiale/
// =============================================

const BASE = 'materiale/';
const LEZIONI = BASE + 'Lezioni/';
const ATTIVITA = BASE + "Attivita' settimanali proposte/";

const DATA = {

  argomenti: [
    { id: 'tutti',      label: 'Tutti',               icon: '📚', col: '#7c3aed' },
    { id: 'fondamenti', label: 'Fondamenti & Logica',  icon: '🔢', col: '#2563eb' },
    { id: 'funzioni',   label: 'Funzioni',             icon: '📈', col: '#059669' },
    { id: 'limiti',     label: 'Limiti & Continuità',  icon: '⟶',  col: '#d97706' },
    { id: 'successioni',label: 'Successioni',          icon: '🔄', col: '#7c3aed' },
    { id: 'continuita', label: 'Teoremi Continuità',   icon: '🔗', col: '#dc2626' },
    { id: 'derivate',   label: 'Derivate',             icon: "𝑓'", col: '#0891b2' },
    { id: 'taylor',     label: 'Taylor & Convessità',  icon: '≈',  col: '#7c3aed' },
    { id: 'integrali',  label: 'Integrali',            icon: '∫',  col: '#be185d' },
    { id: 'edo',        label: 'EDO',                  icon: '⚙️', col: '#065f46' },
    { id: 'esame',      label: 'Esame',                icon: '📝', col: '#eab308' },
    { id: 'pretest',    label: 'Pretest',              icon: '🏁', col: '#eab308' },
  ],

  lezioni: [
    {
      id:'L1', arg:'fondamenti', argLabel:'Fondamenti & Logica',
      titolo:'Introduzione al corso, predicati logici',
      data:'24 set 2025', durata:'90 min',
      desc:'Predicati logici, connettivi, implicazione, negazione, tavole di verità.',
      concetti:['Predicati','Connettivi logici','Implicazione','Negazione'],
      pdf: LEZIONI + 'L1 24 set 2025_ introduzione al corso, predicati logici.pdf',
      json: 'contenuti/lezione_l1.json',
    },
    {
      id:'L2', arg:'fondamenti', argLabel:'Fondamenti & Logica',
      titolo:'Quantificatori, insiemi numerici',
      data:'25 set 2025', durata:'90 min',
      desc:'Quantificatori ∀ ∃. Insiemi ℕ, ℤ, ℚ, ℝ. Assioma di completezza.',
      concetti:['∀ ∃ quantificatori','Numeri reali','Assioma completezza'],
      pdf: LEZIONI + 'L2 25 set 2025_ quantificatori, insiemi numerici.pdf',
      json: 'contenuti/lezione_l2.json',
    },
    {
      id:'L3', arg:'fondamenti', argLabel:'Fondamenti & Logica',
      titolo:'Sup, inf, max, min, funzioni',
      data:'26 set 2025', durata:'120 min',
      desc:'Estremo superiore e inferiore. Massimo e minimo. Introduzione alle funzioni.',
      concetti:['sup e inf','max e min','Maggioranti','Definizione funzione'],
      pdf: LEZIONI + 'L3 26 set 2025_ sup, inf, max, min, funzioni.pdf',
      json: 'contenuti/lezione_l3.json',
    },
    {
      id:'L4', arg:'funzioni', argLabel:'Funzioni',
      titolo:'Funzioni iniettive, suriettive, inversa',
      data:'1 ott 2025', durata:'180 min',
      desc:'Iniettività, suriettività, biettività. Composizione. Funzione inversa.',
      concetti:['Iniettività','Suriettività','Funzione inversa','Composizione'],
      pdf: LEZIONI + "L4 1 ott 2025_ funzioni iniettive, suriettive, operazioni su funzioni, funzione inversa (3 ore).pdf",
      json: 'contenuti/lezione_l4.json',
    },
    {
      id:'L5', arg:'funzioni', argLabel:'Funzioni',
      titolo:'Funzioni limitate, massimi e minimi, funzioni monotone',
      data:'3 ott 2025', durata:'90 min',
      desc:'Funzioni superiormente/inferiormente limitate. Massimi globali. Monotonia.',
      concetti:['Funzioni limitate','Massimo globale','Monotonia stretta'],
      pdf: LEZIONI + "L5 3 ott 2025_ funzioni limitate, massimi e minimi di funzioni, funzioni monotone.pdf",
      json: 'contenuti/lezione_l5.json',
    },
    {
      id:'L6', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Introduzione ai limiti',
      data:'8 ott 2025', durata:'90 min',
      desc:'Definizione ε-δ di limite. Limiti laterali. Forme indeterminate.',
      concetti:['Definizione ε-δ','Limiti laterali','Forme indeterminate'],
      pdf: LEZIONI + 'L6 8 ott 2025_ introduzione ai limiti.pdf',
      json: 'contenuti/lezione_l6.json',
    },
    {
      id:'L7', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Limiti e continuità',
      data:'10 ott 2025', durata:'90 min',
      desc:'Continuità. Punti di discontinuità: prima, seconda e terza specie.',
      concetti:['Continuità','Discontinuità I specie','Discontinuità eliminabile'],
      pdf: LEZIONI + "L7 10 ott 2025_ limiti e continuita'.pdf",
      json: 'contenuti/lezione_l7.json',
    },
    {
      id:'L8', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Limiti con dominio o immagine illimitati',
      data:'16 ott 2025', durata:'90 min',
      desc:"Limiti all'infinito. Asintoti orizzontali, verticali e obliqui.",
      concetti:["Limite all'infinito",'Asintoto orizzontale','Asintoto obliquo'],
      pdf: LEZIONI + 'L8 16 ott 2025_ limiti con domf o imf illimitati.pdf',
      json: 'contenuti/lezione_l8.json',
    },
    {
      id:'L9', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Teoremi sui limiti',
      data:'17 ott 2025', durata:'90 min',
      desc:'Unicità del limite, permanenza del segno, teorema dei carabinieri.',
      concetti:['Unicità del limite','Permanenza segno','Teorema carabinieri'],
      pdf: LEZIONI + 'L9 17 ott 2025_ teoremi sui limiti.pdf',
      json: 'contenuti/lezione_l9.json',
    },
    {
      id:'L10', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Teorema limite funzione composta',
      data:'23 ott 2025', durata:'90 min',
      desc:'Limite della composizione di funzioni. Calcolo di limiti complessi.',
      concetti:['Funzione composta','Sostituzione','Calcolo limiti'],
      pdf: LEZIONI + 'L10 23 ott 2025_ teorema sul limite della  funzione composta.pdf',
      json: 'contenuti/lezione_l10.json',
    },
    {
      id:'L11', arg:'limiti', argLabel:'Limiti & Continuità',
      titolo:'Teorema funzione composta e limiti notevoli',
      data:'24 ott 2025', durata:'90 min',
      desc:'Limiti notevoli: sin(x)/x, (1+1/n)ⁿ=e, limiti logaritmici.',
      concetti:['lim sin(x)/x = 1','Numero e','Limiti logaritmici'],
      pdf: LEZIONI + 'L11 24 ott 2025_ teorema fz composta e limiti notevoli.pdf',
      json: 'contenuti/lezione_l11.json',
    },
    {
      id:'L12', arg:'successioni', argLabel:'Successioni',
      titolo:'Successioni',
      data:'3 nov 2025', durata:'90 min',
      desc:'Definizione di successione. Convergenza, divergenza, oscillazione.',
      concetti:['Successione','Convergenza','Successione di Cauchy'],
      pdf: LEZIONI + 'L12 3 nov 2025_ successioni.pdf',
      json: 'contenuti/lezione_l12.json',
    },
    {
      id:'L13', arg:'successioni', argLabel:'Successioni',
      titolo:'Successione geometrica, teoremi per funzioni continue',
      data:'nov 2025', durata:'90 min',
      desc:'Successione geometrica. Teorema di Weierstrass. Continuità uniforme.',
      concetti:['Successione geometrica','Teorema Weierstrass','Continuità uniforme'],
      pdf: LEZIONI + "L13 nov 2025_ successione geometrica, primi teoremi per fz continue.pdf",
      json: 'contenuti/lezione_l13.json',
    },
    {
      id:'L14', arg:'continuita', argLabel:'Teoremi Continuità',
      titolo:'Teorema di esistenza degli zeri',
      data:'6 nov 2025', durata:'90 min',
      desc:'Teorema degli zeri di Bolzano. Applicazioni alla risoluzione di equazioni.',
      concetti:['Teorema di Bolzano','Zeri di funzione','Bisezione'],
      pdf: LEZIONI + 'L14  6 nov 2025_ teorema esistenza zeri.pdf',
      json: 'contenuti/lezione_l14.json',
    },
    {
      id:'L15', arg:'continuita', argLabel:'Teoremi Continuità',
      titolo:'Teorema valori intermedi, simboli di Landau',
      data:'7 nov 2025', durata:'90 min',
      desc:'Teorema dei valori intermedi. Simboli o-piccolo e O-grande.',
      concetti:['Valori intermedi','o piccolo','O grande','Landau'],
      pdf: LEZIONI + 'L15 7 nov 2025_ teor valori intermedi, simboli di Laundau.pdf',
      json: 'contenuti/lezione_l15.json',
    },
    {
      id:'L16', arg:'continuita', argLabel:'Teoremi Continuità',
      titolo:'Parte principale',
      data:'12 nov 2025', durata:'90 min',
      desc:'Parte principale di una funzione. Ordine di infinitesimo e infinito.',
      concetti:['Parte principale','Ordine infinitesimo','Equivalenza asintotica'],
      pdf: LEZIONI + 'L16 12 nov 2025_ parte principale.pdf',
      json: 'contenuti/lezione_l16.json',
    },
    {
      id:'L17', arg:'derivate', argLabel:'Derivate',
      titolo:'Derivate',
      data:'14 nov 2025', durata:'90 min',
      desc:'Definizione di derivata. Derivate fondamentali. Regole di derivazione.',
      concetti:['Definizione derivata','Derivate elementari','Regola prodotto'],
      pdf: LEZIONI + 'L17 14 nov 2025_derivate.pdf',
      json: 'contenuti/lezione_l17.json',
    },
    {
      id:'L18', arg:'derivate', argLabel:'Derivate',
      titolo:'Punti di non derivabilità',
      data:'20 nov 2025', durata:'90 min',
      desc:'Punti angolosi, cuspidi, flessi a tangente verticale.',
      concetti:['Punto angoloso','Cuspide','Flesso verticale'],
      pdf: LEZIONI + 'L18 20 nov 2025_ punti di non derivabilita.pdf',
      json: 'contenuti/lezione_l18.json',
    },
    {
      id:'L19', arg:'derivate', argLabel:'Derivate',
      titolo:'Teoremi di derivazione',
      data:'21 nov 2025', durata:'90 min',
      desc:"Teorema di Rolle, Lagrange, Cauchy. Regola di De L'Hôpital.",
      concetti:['Teorema di Rolle','Teorema di Lagrange',"De L'Hôpital"],
      pdf: LEZIONI + 'L19 21 nov 2025_ teoremi di derivazione.pdf',
      json: 'contenuti/lezione_l19.json',
    },
    {
      id:'L20', arg:'taylor', argLabel:'Taylor & Convessità',
      titolo:'Sviluppi di Taylor',
      data:'27 nov 2025', durata:'90 min',
      desc:'Formula di Taylor con resto di Peano e Lagrange. Calcolo dei limiti.',
      concetti:['Formula di Taylor','Resto di Peano','Approssimazione'],
      pdf: LEZIONI + 'L20 27 nov 2025_ sviluppi di Taylor.pdf',
      json: 'contenuti/lezione_l20.json',
    },
    {
      id:'L21', arg:'taylor', argLabel:'Taylor & Convessità',
      titolo:'McLaurin, concavità, convessità, flessi',
      data:'28 nov 2025', durata:'90 min',
      desc:'Sviluppi di McLaurin delle funzioni elementari. Convessità. Flessi.',
      concetti:['McLaurin','Convessità','Concavità','Flesso'],
      pdf: LEZIONI + 'L21 28 nov 2025_ sviluppi di McLaurin, concavita, convessita, flessi.pdf',
      json: 'contenuti/lezione_l21.json',
    },
    {
      id:'L22', arg:'taylor', argLabel:'Taylor & Convessità',
      titolo:'Convessità con Taylor',
      data:'3 dic 2025', durata:'90 min',
      desc:'Studio della convessità tramite Taylor. Studio completo di funzione.',
      concetti:['Convessità con Taylor','Studio funzione','Grafico'],
      pdf: LEZIONI + 'L22 3 dic 2025_ convessitaÂ  con  Taylor.pdf',
      json: 'contenuti/lezione_l22.json',
    },
    {
      id:'L23', arg:'integrali', argLabel:'Integrali',
      titolo:'Integrali indefiniti',
      data:'4 dic 2025', durata:'90 min',
      desc:'Primitiva e integrale indefinito. Sostituzione, per parti.',
      concetti:['Primitiva','Integrazione per sostituzione','Per parti'],
      pdf: LEZIONI + 'L23 4 dic 2025_ integrali indefiniti.pdf',
      json: 'contenuti/lezione_l23.json',
    },
    {
      id:'L24', arg:'integrali', argLabel:'Integrali',
      titolo:'Integrale definito',
      data:'5 dic 2025', durata:'90 min',
      desc:'Integrale di Riemann. Somme di Riemann. Proprietà e integrabilità.',
      concetti:['Integrale di Riemann','Somme Riemann','Proprietà'],
      pdf: LEZIONI + 'L24 5 dic 2025_ integrale definito.pdf',
      json: 'contenuti/lezione_l24.json',
    },
    {
      id:'L25', arg:'integrali', argLabel:'Integrali',
      titolo:'Teorema Fondamentale del Calcolo Integrale',
      data:'11 dic 2025', durata:'90 min',
      desc:'TFCI: funzione integrale, derivabilità. Formula di Newton-Leibniz.',
      concetti:['TFCI','Funzione integrale','Newton-Leibniz'],
      pdf: LEZIONI + 'L25 11 dic 2025_ TFCI.pdf',
      json: 'contenuti/lezione_l25.json',
    },
    {
      id:'L26', arg:'integrali', argLabel:'Integrali',
      titolo:'Integrali impropri',
      data:'12 dic 2025', durata:'90 min',
      desc:'Integrali impropri su intervalli illimitati o con singolarità.',
      concetti:['Integrale improprio','Convergenza','Criterio confronto'],
      pdf: LEZIONI + 'L26 12 dic 2025_ integrali impropri.pdf',
      json: 'contenuti/lezione_l26.json',
    },
    {
      id:'EDO', arg:'edo', argLabel:'EDO',
      titolo:'Equazioni Differenziali Ordinarie',
      data:'2025', durata:'180 min',
      desc:'EDO del I e II ordine. EDO separabili, lineari, omogenee.',
      concetti:['EDO I ordine','EDO separabili','EDO lineari','Cauchy'],
      pdf: LEZIONI + 'EDO.pdf',
      json: 'contenuti/lezione_edo.json',
    },
    {
      id:'EsFin', arg:'esame', argLabel:'Esame',
      titolo:'Esercitazione finale - 8 gen 2026',
      data:'8 gen 2026', durata:'120 min',
      desc:'Riepilogo completo di tutti gli argomenti del corso.',
      concetti:['Riepilogo','Esercizi esame','Strategie'],
      pdf: LEZIONI + 'Esercitazione finale 8 gen 2026.pdf',
      json: 'contenuti/lezione_esfin.json',
    },
  ],

  settimane: [
    {
      n:1, titolo:'Itinere 1 - Fondamenti', arg:'fondamenti',
      desc:'Prove d\'itinere degli anni passati sui fondamenti: logica, insiemi, funzioni.',
      esercizi:[
        {nome:'Itinere 1 - 2021/22',    tipo:'itinere',
         pdf:  ATTIVITA+"Settimana 1/Itinere 1 2021-22.pdf",
         sol:  ATTIVITA+"Settimana 1/Itinere 1 2021-22-svolgimento.pdf",
         json: "contenuti/esercizio_s1_Itinere_1_2021-22.json"},
        {nome:'Itinere 1 - 2022/23',    tipo:'itinere',
         pdf:  ATTIVITA+"Settimana 1/Itinere1 2022-23.pdf",
         sol:  ATTIVITA+"Settimana 1/Itinere 1 2022-23_svolgimento.pdf",
         json: "contenuti/esercizio_s1_Itinere1_2022-23.json"},
        {nome:'Itinere 1 - 2023/24',    tipo:'itinere',
         pdf:  ATTIVITA+"Settimana 1/Itinere1-2023-24.pdf",
         sol:  ATTIVITA+"Settimana 1/Itinere1-2023-24_svolgimento.pdf",
         json: "contenuti/esercizio_s1_Itinere1-2023-24.json"},
      ]
    },
    {
      n:2, titolo:'Funzioni - Esercizi e Itinere', arg:'funzioni',
      desc:'Esercizi su funzioni, inf/sup, itinere 1 del 2024/25.',
      esercizi:[
        {nome:'Esercizi su funzioni',           tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 2/Esercizi su funzioni.pdf",
         sol: ATTIVITA+"Settimana 2/Esercizi su funzioni_risposte.pdf",
         json:"contenuti/esercizio_s2_Esercizi_su_funzioni.json"},
        {nome:'Appello gen. 2020 - inf/sup',    tipo:'appello',
         pdf: ATTIVITA+"Settimana 2/Es 2 appello gennaio 2020.pdf",
         sol: ATTIVITA+"Settimana 2/Es su inf sup appello gennaio 2020_svolgimento.pdf",
         json:"contenuti/esercizio_s2_Es_2_appello_gennaio_2020.json"},
        {nome:'Itinere 1 - 2024/25',           tipo:'itinere',
         pdf: ATTIVITA+"Settimana 2/Itinere1-2024-25.pdf",
         sol: ATTIVITA+"Settimana 2/Itinere1-2024-25_svolgimento.pdf",
         json:"contenuti/esercizio_s2_Itinere1-2024-25.json"},
      ]
    },
    {
      n:3, titolo:'Quantificatori e Sup', arg:'fondamenti',
      desc:'Mini esercitazioni su quantificatori e dimostrazione di sup.',
      esercizi:[
        {nome:'Mini-esercitazione quantificatori', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 3/mini-esercitazione-quantificatori.pdf",
         sol: ATTIVITA+"Settimana 3/mini-esercitazione-quantificatori_risposte.pdf",
         json:"contenuti/esercizio_s3_mini-esercitazione-quantificatori.json"},
        {nome:'Dimostrazione di sup',              tipo:'dimostrazione',
         pdf: ATTIVITA+"Settimana 3/dimostrazione di sup.pdf",
         sol: ATTIVITA+"Settimana 3/dimostrazione di sup_risposta.pdf",
         json:"contenuti/esercizio_s3_dimostrazione_di_sup.json"},
      ]
    },
    {
      n:4, titolo:'Teoremi di Confronto', arg:'limiti',
      desc:'Applicazione dei teoremi di confronto al calcolo dei limiti.',
      esercizi:[
        {nome:'Teoremi di confronto', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 4/Teoremi di confronto.pdf",
         sol: ATTIVITA+"Settimana 4/Teoremi di confronto_svolgimento.pdf",
         json:"contenuti/esercizio_s4_Teoremi_di_confronto.json"},
      ]
    },
    {
      n:5, titolo:'Limiti - Non-esistenza e Itinere 2', arg:'limiti',
      desc:'Inesistenza dei limiti, itinere 2 del 2022/23.',
      esercizi:[
        {nome:'Non esistenza del limite', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 5/Esercizio_non_esisitenza_limite.pdf",
         sol: ATTIVITA+"Settimana 5/Esercizio_non_esistenza_limite_svolgimento.pdf",
         json:"contenuti/esercizio_s5_Esercizio_non_esisitenza_limite.json"},
        {nome:'Itinere 2 - 2022/23',      tipo:'itinere',
         pdf: ATTIVITA+"Settimana 5/22-23-Itinere2.pdf",
         sol: ATTIVITA+"Settimana 5/22-23-Itinere2-svolgimento.pdf",
         json:"contenuti/esercizio_s5_22-23-Itinere2.json"},
      ]
    },
    {
      n:6, titolo:'Successioni e Appelli', arg:'successioni',
      desc:'Esercizi su successioni, appelli di gennaio 2023.',
      esercizi:[
        {nome:'Appello con successione',  tipo:'appello',
         pdf: ATTIVITA+"Settimana 6/Appello con successione.pdf",
         sol: ATTIVITA+"Settimana 6/Appello con successione_svolgimento.pdf",
         json:"contenuti/esercizio_s6_Appello_con_successione.json"},
        {nome:'Appello gennaio 2023',     tipo:'appello',
         pdf: ATTIVITA+"Settimana 6/Appello gennaio 2023.pdf",
         sol: ATTIVITA+"Settimana 6/Appello gennaio 2023_svolgimento.pdf",
         json:"contenuti/esercizio_s6_Appello_gennaio_2023.json"},
        {nome:'Itinere 2 - 2024/25',     tipo:'itinere',
         pdf: ATTIVITA+"Settimana 6/Itinere2-24-25.pdf",
         sol: ATTIVITA+"Settimana 6/Itinere2-24-25_svolgimento.pdf",
         json:"contenuti/esercizio_s6_Itinere2-24-25.json"},
      ]
    },
    {
      n:7, titolo:'Landau - Esercitazione e Itinere', arg:'continuita',
      desc:'Esercitazione con simboli di Landau, itinere 2 del 2023/24.',
      esercizi:[
        {nome:'Esercitazione con Landau', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 7/Esercitazione con Landau.pdf",
         sol: ATTIVITA+"Settimana 7/Esercitazione con Landau_svolgimento.pdf",
         json:"contenuti/esercizio_s7_Esercitazione_con_Landau.json"},
        {nome:'Itinere 2 - 2023/24',     tipo:'itinere',
         pdf: ATTIVITA+"Settimana 7/Itinere2-23-24.pdf",
         sol: ATTIVITA+"Settimana 7/Itinere2-23-24-svolgimento.pdf",
         json:"contenuti/esercizio_s7_Itinere2-23-24.json"},
      ]
    },
    {
      n:8, titolo:'Derivabilità', arg:'derivate',
      desc:'Mini esercitazione sulla derivabilità.',
      esercizi:[
        {nome:'Mini-esercitazione derivabilità', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 8/mini-esercitazione-derivabilita.pdf",
         sol: ATTIVITA+"Settimana 8/mini-esercitazione-derivabilita_svolgimento.pdf",
         json:"contenuti/esercizio_s8_mini-esercitazione-derivabilita.json"},
      ]
    },
    {
      n:9, titolo:'Taylor - Esercizi e Itinere 3', arg:'taylor',
      desc:'Esercizi con sviluppi di Taylor, itinere 3 del 2024/25.',
      esercizi:[
        {nome:'Esercizi con Taylor',  tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 9/Esercizi con Taylor.pdf",
         sol: ATTIVITA+"Settimana 9/Esercizi con Taylor_svolgimento.pdf",
         json:"contenuti/esercizio_s9_Esercizi_con_Taylor.json"},
        {nome:'Itinere 3 - 2024/25', tipo:'itinere',
         pdf: ATTIVITA+"Settimana 9/Itinere3-24-25.pdf",
         sol: ATTIVITA+"Settimana 9/Itinere3-24-25_svolgimento.pdf",
         json:"contenuti/esercizio_s9_Itinere3-24-25.json"},
      ]
    },
    {
      n:10, titolo:'Integrali - Esercizi e Itinere 3', arg:'integrali',
      desc:'Integrali impropri da appelli, funzione integrale, esercitazione finale.',
      esercizi:[
        {nome:'Funzione integrale',                tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 10/Funzione integrale_testo_e_svolgimento.pdf", sol:null,
         json:"contenuti/esercizio_s10_Funzione_integrale_testo_e_svolgimento.json"},
        {nome:'Integrale improprio - sett. 2021',  tipo:'appello',
         pdf: ATTIVITA+"Settimana 10/Integrale improprio da appello settembre 2021.pdf", sol:null,
         json:"contenuti/esercizio_s10_Integrale_improprio_da_appello_settembre_2021.json"},
        {nome:'Integrale improprio - gen. 2024',   tipo:'appello',
         pdf: ATTIVITA+"Settimana 10/integrale improprio da appello gen 2024_tris.pdf", sol:null,
         json:"contenuti/esercizio_s10_integrale_improprio_da_appello_gen_2024_tris.json"},
        {nome:'Esercitazione finale',              tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 10/Esercitazione finale testo_e_svolgimento.pdf", sol:null,
         json:"contenuti/esercizio_s10_Esercitazione_finale_testo_e_svolgimento.json"},
        {nome:'Itinere 3 - 2023/24',              tipo:'itinere',
         pdf: ATTIVITA+"Settimana 10/Itinere3-23-24-testo-e-svolgimento.pdf", sol:null,
         json:"contenuti/esercizio_s10_Itinere3-23-24-testo-e-svolgimento.json"},
      ]
    },
    {
      n:11, titolo:'EDO, Complessi, Integrali Impropri', arg:'edo',
      desc:'Esercitazione finale su EDO, numeri complessi, integrali impropri.',
      esercizi:[
        {nome:'EDO, Complessi, Integrali - 18 dic 2025', tipo:'esercitazione',
         pdf: ATTIVITA+"Settimana 11/EDO, complessi, integrali impropri 18 dic 2025.pdf", sol:null,
         json:"contenuti/esercizio_s11_EDO,_complessi,_integrali_impropri_18_dic_2025.json"},
      ]
    },
  ],

  formule: [
    {cat:'Limiti Notevoli', titolo:'Limite fondamentale seno',
     f:'\\lim_{x \\to 0} \\dfrac{\\sin x}{x} = 1',
     nota:'Valido anche per tan(x)/x e arcsin(x)/x'},
    {cat:'Limiti Notevoli', titolo:'Numero di Nepero',
     f:'\\lim_{n \\to \\infty} \\left(1 + \\dfrac{1}{n}\\right)^n = e \\approx 2.71828',
     nota:'Generalizzazione: \\(\\lim_{x\\to 0}(1+x)^{1/x}=e\\)'},
    {cat:'Limiti Notevoli', titolo:'Limite logaritmico',
     f:'\\lim_{x \\to 0} \\dfrac{\\ln(1+x)}{x} = 1',
     nota:'Equivalentemente: \\(\\ln(1+x)\\sim x\\) per \\(x\\to 0\\)'},
    {cat:'Derivate', titolo:'Regola del prodotto',
     f:"(f \\cdot g)' = f'g + fg'",
     nota:"Si estende: \\((fgh)'=f'gh+fg'h+fgh'\\)"},
    {cat:'Derivate', titolo:'Regola del quoziente',
     f:"\\left(\\dfrac{f}{g}\\right)' = \\dfrac{f'g - fg'}{g^2}",
     nota:'Valida dove \\(g\\neq 0\\)'},
    {cat:'Derivate', titolo:'Regola della catena',
     f:"(f\\circ g)'(x) = f'(g(x))\\cdot g'(x)",
     nota:'Essenziale per derivare composizioni'},
    {cat:'Taylor', titolo:'Formula di Taylor',
     f:'f(x) = \\sum_{k=0}^{n}\\dfrac{f^{(k)}(x_0)}{k!}(x-x_0)^k + o((x-x_0)^n)',
     nota:'Resto di Peano: \\(o((x-x_0)^n)\\)'},
    {cat:'Taylor', titolo:'McLaurin di sin(x)',
     f:'\\sin x = x - \\dfrac{x^3}{6} + \\dfrac{x^5}{120} - \\cdots',
     nota:'Solo termini dispari'},
    {cat:'Taylor', titolo:'McLaurin di cos(x)',
     f:'\\cos x = 1 - \\dfrac{x^2}{2} + \\dfrac{x^4}{24} - \\cdots',
     nota:'Solo termini pari'},
    {cat:'Taylor', titolo:'McLaurin di eˣ',
     f:'e^x = 1 + x + \\dfrac{x^2}{2} + \\dfrac{x^3}{6} + \\cdots = \\sum_{n=0}^{\\infty}\\dfrac{x^n}{n!}',
     nota:'Converge per ogni \\(x\\in\\mathbb{R}\\)'},
    {cat:'Integrali', titolo:'Integrazione per parti',
     f:"\\int f'(x)\\,g(x)\\,dx = f(x)g(x) - \\int f(x)\\,g'(x)\\,dx",
     nota:'Mnemonica LIATE: Logaritmi, Inversa trig, Algebriche, Trig, Esponenziali'},
    {cat:'Integrali', titolo:'Newton-Leibniz',
     f:'\\int_a^b f(x)\\,dx = F(b) - F(a)',
     nota:'\\(F\\) è una qualsiasi primitiva di \\(f\\)'},
    {cat:'EDO', titolo:'EDO lineare I ordine',
     f:"y' + a(x)y = b(x) \\implies y = e^{-A(x)}\\!\\left(C + \\int b(x)e^{A(x)}dx\\right)",
     nota:'\\(A(x)=\\int a(x)\\,dx\\)'},
  ],

  teoremi: [
    {nome:'Teorema di Bolzano (Zeri)', arg:'Continuità',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua, \\(f(a)\\cdot f(b)<0\\)',
     tesi:'Esiste \\(c\\in(a,b)\\) con \\(f(c)=0\\)',
     idea:'Si applica il metodo di bisezione iterativamente. La successione di intervalli converge a un punto \\(c\\) che per continuità soddisfa \\(f(c)=0\\).',
     uso:'Dimostrare l\'esistenza di radici di equazioni. Utile in analisi numerica.'},
    {nome:'Teorema di Weierstrass', arg:'Continuità',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua su intervallo chiuso e limitato',
     tesi:'\\(f\\) ha massimo e minimo assoluti su \\([a,b]\\)',
     idea:'L\'immagine di un compatto tramite una funzione continua è compatta, quindi chiusa e limitata, dunque ha massimo e minimo.',
     uso:'Garantire l\'esistenza di ottimi. Fondamentale per l\'ottimizzazione.'},
    {nome:'Teorema di Rolle', arg:'Derivate',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua su \\([a,b]\\), derivabile in \\((a,b)\\), \\(f(a)=f(b)\\)',
     tesi:'Esiste \\(c\\in(a,b)\\) con \\(f\'(c)=0\\)',
     idea:'Per Weierstrass \\(f\\) ha max e min. Se entrambi ai bordi \\(f\\) è costante. Altrimenti uno è interno, e lì la derivata è zero.',
     uso:'Base per dimostrare Lagrange. Usato per studiare il numero di zeri.'},
    {nome:'Teorema di Lagrange (Valor Medio)', arg:'Derivate',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua su \\([a,b]\\), derivabile in \\((a,b)\\)',
     tesi:'Esiste \\(c\\in(a,b)\\) con \\(f\'(c)=\\dfrac{f(b)-f(a)}{b-a}\\)',
     idea:'Si applica Rolle a \\(g(x)=f(x)-\\frac{f(b)-f(a)}{b-a}(x-a)\\) che soddisfa \\(g(a)=g(b)\\).',
     uso:'Monotonia (\\(f\'\\geq 0\\Rightarrow f\\) crescente), stime, disuguaglianze.'},
    {nome:'Teorema dei Carabinieri', arg:'Limiti',
     ipotesi:'\\(g(x)\\leq f(x)\\leq h(x)\\) in un intorno di \\(x_0\\), \\(\\lim g=\\lim h=L\\)',
     tesi:'\\(\\lim_{x\\to x_0}f(x)=L\\)',
     idea:'Per \\(\\varepsilon>0\\), \\(\\delta\\) tale che \\(|g(x)-L|<\\varepsilon\\) e \\(|h(x)-L|<\\varepsilon\\) implica \\(|f(x)-L|<\\varepsilon\\).',
     uso:'Calcolare limiti di funzioni difficili intrappolandole tra due funzioni facili.'},
    {nome:'Teorema Fondamentale del Calcolo (TFCI)', arg:'Integrali',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua',
     tesi:'\\(F(x)=\\int_a^x f(t)\\,dt\\) è derivabile e \\(F\'(x)=f(x)\\). Inoltre \\(\\int_a^b f=G(b)-G(a)\\) per ogni primitiva \\(G\\).',
     idea:'\\(F(x+h)-F(x)=\\int_x^{x+h}f(t)\\,dt\\approx f(x)h\\) per continuità. Quindi \\(F\'(x)=f(x)\\).',
     uso:'Calcolare integrali definiti tramite primitive. Collega derivazione e integrazione.'},
    {nome:"Regola di De L'Hôpital", arg:'Derivate',
     ipotesi:'\\(\\lim f=\\lim g=0\\) o \\(\\pm\\infty\\), \\(g\'\\neq 0\\)',
     tesi:"\\(\\lim\\dfrac{f}{g}=\\lim\\dfrac{f'}{g'}\\) se il secondo limite esiste",
     idea:'Segue dal Teorema di Cauchy. Si applica solo nelle forme \\(0/0\\) o \\(\\infty/\\infty\\).',
     uso:'Calcolare limiti in forma indeterminata. Utile per confrontare ordini di infinitesimo.'},
    {nome:'Teorema dei Valori Intermedi', arg:'Continuità',
     ipotesi:'\\(f:[a,b]\\to\\mathbb{R}\\) continua, \\(k\\) compreso tra \\(f(a)\\) e \\(f(b)\\)',
     tesi:'Esiste \\(c\\in(a,b)\\) con \\(f(c)=k\\)',
     idea:'Si riduce al Teorema degli Zeri applicato a \\(g(x)=f(x)-k\\).',
     uso:'Dimostrare l\'esistenza di soluzioni di equazioni. Fondamentale in analisi.'},
  ],

  mclaurin: [
    {fn:'e^x',        f:'1 + x + \\dfrac{x^2}{2!} + \\dfrac{x^3}{3!} + \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{x^n}{n!}', dom:'\\(x\\in\\mathbb{R}\\)'},
    {fn:'\\sin x',    f:'x - \\dfrac{x^3}{3!} + \\dfrac{x^5}{5!} - \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(-1)^n x^{2n+1}}{(2n+1)!}', dom:'\\(x\\in\\mathbb{R}\\)'},
    {fn:'\\cos x',    f:'1 - \\dfrac{x^2}{2!} + \\dfrac{x^4}{4!} - \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(-1)^n x^{2n}}{(2n)!}', dom:'\\(x\\in\\mathbb{R}\\)'},
    {fn:'\\ln(1+x)',  f:'x - \\dfrac{x^2}{2} + \\dfrac{x^3}{3} - \\cdots = \\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^{n+1}x^n}{n}', dom:'\\(x\\in(-1,1]\\)'},
    {fn:'\\dfrac{1}{1-x}', f:'1+x+x^2+\\cdots = \\displaystyle\\sum_{n=0}^{\\infty}x^n', dom:'\\(|x|<1\\)'},
    {fn:'(1+x)^\\alpha', f:'1+\\alpha x+\\dfrac{\\alpha(\\alpha-1)}{2!}x^2+\\cdots', dom:'\\(|x|<1\\)'},
    {fn:'\\arctan x', f:'x - \\dfrac{x^3}{3} + \\dfrac{x^5}{5} - \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(-1)^n x^{2n+1}}{2n+1}', dom:'\\(|x|\\leq 1\\)'},
    {fn:'\\sinh x',   f:'x + \\dfrac{x^3}{3!} + \\dfrac{x^5}{5!} + \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{x^{2n+1}}{(2n+1)!}', dom:'\\(x\\in\\mathbb{R}\\)'},
    {fn:'\\cosh x',   f:'1 + \\dfrac{x^2}{2!} + \\dfrac{x^4}{4!} + \\cdots = \\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{x^{2n}}{(2n)!}', dom:'\\(x\\in\\mathbb{R}\\)'},
  ],

  quiz: [
    {arg:'limiti', dif:'base',
     d:'\\(\\lim_{x\\to 0}\\dfrac{\\sin x}{x} = ?\\)',
     opts:['0','1','\\(\\infty\\)','Non esiste'], ok:1,
     spieg:'Limite notevole fondamentale. Si dimostra geometricamente: \\(\\sin x < x < \\tan x\\) per \\(x\\in(0,\\pi/2)\\), dividendo per \\(\\sin x\\) e passando al limite.'},
    {arg:'derivate', dif:'base',
     d:"Qual è \\(\\dfrac{d}{dx}e^x\\) ?",
     opts:["\\(e^x\\)","\\(xe^{x-1}\\)","\\(\\frac{1}{e^x}\\)","\\(e^x\\ln x\\)"], ok:0,
     spieg:'\\(f\'(x)=e^x\\). La funzione esponenziale è l\'unica funzione (a meno di costanti) uguale alla propria derivata.'},
    {arg:'integrali', dif:'medio',
     d:'Cosa afferma il TFCI?',
     opts:['La derivata di un integrale è zero',
           '\\(\\int_a^b f = F(b)-F(a)\\) dove \\(F\'=f\\)',
           'Ogni funzione continua è uguale alla propria primitiva',
           "L'integrale di una costante è zero"], ok:1,
     spieg:'Il TFCI collega integrazione e derivazione: \\(\\int_a^b f(x)\\,dx=F(b)-F(a)\\) dove \\(F\\) è una primitiva di \\(f\\). La funzione integrale \\(F(x)=\\int_a^x f(t)\\,dt\\) soddisfa \\(F\'=f\\).'},
    {arg:'taylor', dif:'medio',
     d:'McLaurin di \\(e^x\\) al 3° ordine:',
     opts:['\\(1+x+x^2+x^3+o(x^3)\\)',
           '\\(1+x+\\frac{x^2}{2}+\\frac{x^3}{6}+o(x^3)\\)',
           '\\(x+\\frac{x^3}{6}+o(x^3)\\)',
           '\\(1-x+\\frac{x^2}{2}-\\frac{x^3}{6}+o(x^3)\\)'], ok:1,
     spieg:'\\(e^x=\\sum_{n=0}^\\infty \\frac{x^n}{n!}\\). I coefficienti \\(\\frac{1}{n!}\\) vengono dal fatto che \\((e^x)^{(n)}|_{x=0}=1\\) per ogni \\(n\\).'},
    {arg:'fondamenti', dif:'base',
     d:'\\(\\sup A = M\\) significa che:',
     opts:['\\(M\\) è il massimo di \\(A\\)',
           '\\(M\\) è il più piccolo maggiorante di \\(A\\)',
           '\\(M\\) è il più grande elemento di \\(A\\)',
           '\\(M\\) è il minimo di \\(A\\)'], ok:1,
     spieg:'\\(\\sup A\\) = minimo dei maggioranti. Non coincide col massimo se \\(A\\) è aperto: \\(\\sup(0,1)=1\\) ma \\(1\\notin(0,1)\\). Esiste sempre per l\'assioma di completezza di \\(\\mathbb{R}\\).'},
    {arg:'derivate', dif:'avanzato',
     d:'Teorema di Lagrange: conclusione?',
     opts:['Se \\(f(a)=f(b)\\) allora \\(\\exists c: f\'(c)=0\\)',
           '\\(\\exists c\\in(a,b): f\'(c)=\\frac{f(b)-f(a)}{b-a}\\)',
           'Se \\(f\\) è derivabile allora è continua',
           'La derivata di una costante è zero'], ok:1,
     spieg:'Lagrange garantisce l\'esistenza di un punto \\(c\\) dove la tangente è parallela alla secante tra \\((a,f(a))\\) e \\((b,f(b))\\). Conseguenze: monotonia (\\(f\'\\geq 0\\Leftrightarrow f\\) crescente), stima degli incrementi.'},
    {arg:'limiti', dif:'medio',
     d:'Quale delle seguenti è una forma indeterminata?',
     opts:['\\(0\\cdot 5\\)','\\(\\infty-\\infty\\)','\\(1^{100}\\)','\\(0+\\infty\\)'], ok:1,
     spieg:'Le forme indeterminate sono: \\(\\frac{0}{0},\\frac{\\infty}{\\infty},0\\cdot\\infty,\\infty-\\infty,1^\\infty,0^0,\\infty^0\\). Per \\(\\infty-\\infty\\) il risultato dipende dalla "velocità" con cui i due addendi tendono a \\(\\infty\\).'},
    {arg:'integrali', dif:'avanzato',
     d:'\\(\\int_1^{+\\infty}\\frac{1}{x^p}dx\\) converge quando:',
     opts:['\\(p>0\\)','\\(p>1\\)','\\(p\\geq 1\\)','\\(p<1\\)'], ok:1,
     spieg:'Per \\(p\\neq 1\\): \\(\\int_1^{+\\infty}x^{-p}dx=\\left[\\frac{x^{1-p}}{1-p}\\right]_1^{+\\infty}\\). Converge \\(\\Leftrightarrow 1-p<0\\Leftrightarrow p>1\\). Per \\(p=1\\): \\(\\int_1^{+\\infty}\\frac{dx}{x}=[\\ln x]_1^{+\\infty}=+\\infty\\).'},
    {arg:'successioni', dif:'medio',
     d:'Una successione monotona crescente e superiormente limitata è:',
     opts:['Divergente','Oscillante','Convergente','Non è detto'], ok:2,
     spieg:'Teorema di Weierstrass per successioni: ogni successione monotona e limitata è convergente. Se è crescente e sup-limitata, converge al proprio \\(\\sup\\) dei valori.'},
    {arg:'taylor', dif:'avanzato',
     d:'McLaurin di \\(\\ln(1+x)\\) al 2° ordine:',
     opts:['\\(x+\\frac{x^2}{2}+o(x^2)\\)',
           '\\(x-\\frac{x^2}{2}+o(x^2)\\)',
           '\\(1+x-\\frac{x^2}{2}+o(x^2)\\)',
           '\\(-x+\\frac{x^2}{2}+o(x^2)\\)'], ok:1,
     spieg:'\\(\\ln(1+x)=x-\\frac{x^2}{2}+\\frac{x^3}{3}-\\cdots\\). Si ottiene integrando \\(\\frac{1}{1+x}=1-x+x^2-\\cdots\\) termine a termine. Oppure calcolando le derivate: \\(f\'(0)=1\\), \\(f\'\'(0)=-1\\).'},
  ],
};
